Add French language
mhausenblas/5stardata.info pull request #29
Opened 2016-10-03 07:36 UTC by bmenant

If someone could review and check it out, that’d be appreciated. 

I’m not quite sure about _pattern/modèle_. It’s hard to understand that one if you have no clue what a _pattern_ means over here. Most of the time, the English word _pattern_ is used in French. But few people actually understand... so I went for the French word _modèle_. A note/link/example would be much appreciated though.

2016-10-04 07:19 UTC, jgkim requested changes
There are a few redirection errors to be corrected.

2016-10-04 07:19 UTC, jgkim commented on fr/examples/gtd-4.html
> +- /en/examples/gtd-4.html
The line 3 should be `/fr/examples/gtd-4.html`.

2016-10-04 07:19 UTC, jgkim commented on fr/examples/gtd-4.html
> +- /gtd-4.html
The line 4 should be deleted.

2016-10-04 07:19 UTC, jgkim commented on fr/examples/gtd-5.html
> +- /en/examples/gtd-5.html
The same thing goes here. This should be `/fr/examples/gtd-5.html`.

2016-10-04 07:19 UTC, jgkim commented on fr/examples/gtd-5.html
> +- /gtd-5.html
This should be deleted.

2016-10-04 07:19 UTC, jgkim commented on fr/index.md
> +redirect_from: /
This should be `redirect_from: /fr/`.

2016-10-04 07:22 UTC, jgkim commented
@bmenant I cannot read French so I cannot review the content. If you know someone can review the content, please ping him or her here. In the meantime, please fix the errors mentioned above. Thank you for the PR. :)

2016-10-07 11:28 UTC, bmenant commented
@jgkim Errors fixed https://github.com/mhausenblas/5stardata.info/pull/29/commits/7ccfaf74e4b59d19759cbf66c46fb09c79e63726

2016-12-11 16:28 UTC, jgkim approved these changes

2016-12-11 16:28 UTC, merged